CREATE DATABASE Sistema_De_Ventas;
GO


USE Sistema_De_Ventas;
GO

SELECT * FROM USUARIO



-- 1. TABLA ROL  --
CREATE TABLE ROL (
IDRol INT PRIMARY KEY IDENTITY,
Descripcion VARCHAR (50),
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO


-- 2. TABLA PERMISOS --
CREATE TABLE PERMISO(
IDPermiso INT PRIMARY KEY IDENTITY,
IDRol INT REFERENCES ROL(IDRol),
NombreMenu VARCHAR(100),
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO


-- 3. TABLA PROVEEDOR --
CREATE TABLE PROVEEDOR (
IDProveedor INT PRIMARY KEY IDENTITY,
Documento VARCHAR (50),
RazonSocial VARCHAR(50),
Correo VARCHAR(50),
Telefono VARCHAR(50),
Estado BIT,
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO


-- 4. TABLA CLIENTE --
CREATE TABLE CLIENTE (
IDCliente INT PRIMARY KEY IDENTITY,
Documento VARCHAR (50),
NombreCompleto VARCHAR(50),
Correo VARCHAR(50),
Telefono VARCHAR(50),
Estado BIT,
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO

INSERT INTO ROL(Descripcion)
VALUES ('Administrador')
GO

INSERT INTO USUARIO(Documento, NombreCompleto,Correo,Clave,IDRol,Estado) 
VALUES ('101010', 'ADMIN','@gmail.com', '12345',1,1)
GO

-- 5. TABLA USUARIO -- 
CREATE TABLE USUARIO (
IDUsuario INT PRIMARY KEY IDENTITY,
Documento VARCHAR (50),
NombreCompleto VARCHAR(50),
Correo VARCHAR(50),
Clave VARCHAR(50),
IDRol INT REFERENCES ROL(IDRol),
Estado BIT,
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO



-- 6. TABLA CATEGORIA -- 
CREATE TABLE CATEGORIA(
IDCategoria INT PRIMARY KEY IDENTITY,
Descripcion VARCHAR(100),
Estado BIT,
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO


-- 7. TABLA PRODUCTO -- 
CREATE TABLE PRODUCTO(
IDProducto INT PRIMARY KEY IDENTITY,
Codigo VARCHAR(50), 
Nombre VARCHAR(50),
Descripcion VARCHAR(100),
IDCategoria INT REFERENCES CATEGORIA(IDCategoria),
Stock INT NOT NULL DEFAULT 0,
PrecioCompra DECIMAL(10,2) DEFAULT 0,
PrecioVenta DECIMAL(10,2) DEFAULT 0,
Estado BIT,
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO


-- 8. TABLA COMPRA --
CREATE TABLE COMPRA (
IDCompra INT PRIMARY KEY IDENTITY,
IDUsuario INT REFERENCES USUARIO(IDUsuario),
IDProveedor INT REFERENCES PROVEEDOR(IDProveedor),
TipoDocumento VARCHAR (50),
NumeroDocumento VARCHAR(50),
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO




-- 9. TABLA DETALLE_COMPRA --
CREATE TABLE DETALLE_COMPRA (
IDDetalleCompra INT PRIMARY KEY IDENTITY,
IDCompra INT REFERENCES COMPRA(IDCompra),
IDProducto INT REFERENCES PRODUCTO(IDProducto),
PrecioCompra DECIMAL(10,2) DEFAULT 0,
PrecioVenta DECIMAL(10,2) DEFAULT 0,
Cantidad INT,
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO


-- 10. TABLA VENTA -- 
CREATE TABLE VENTA (
IDVenta INT PRIMARY KEY IDENTITY,
IDUsuario INT REFERENCES USUARIO(IDUsuario),
TipoDocumento VARCHAR (50),
NumeroDocumento VARCHAR(50),
DocumentoCliente VARCHAR(50),
NombreCliente VARCHAR(100),
MontoPago DECIMAL(10,2), 
MontoCambio DECIMAL(10,2),
MontoTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO


-- 11. TABLE DETALLE VENTA --
CREATE TABLE DETALLE_VENTA (
IDDetalleVenta INT PRIMARY KEY IDENTITY,
IDVenta INT REFERENCES VENTA(IDVenta),
IDProducto INT REFERENCES PRODUCTO(IDProducto),
PrecioVenta DECIMAL(10,2),
Cantidad INT,
SubTotal DECIMAL(10,2),
FechaRegistro DATETIME DEFAULT GETDATE()
);
GO

CREATE TABLE NEGOCIO(
IDNegocio INT PRIMARY KEY,
Nombre VARCHAR(60),
RUC VARCHAR(60),
Direccion VARCHAR(60),
Logo VARBINARY(MAX)NULL
)
GO

SELECT * FROM NEGOCIO
GO

USE Sistema_De_Ventas

-- PARA ABRIR LA CONEXION Y SELECCIONAR LOS DATOS DE LA TABLA NEGOCIO --
select IDNegocio, Nombre, RUC, Direccion from NEGOCIO where IDNegocio = 1
go

-- Logo select 
select Logo from NEGOCIO where IDNegocio = 1
go